### ISSUE TITLE
[BUG] Benchmarks run same test 12 times

### ISSUE THREAD

**Issue by magnushiie** [LdDl/ch#28]
**Describe the bug**
The benchmarks (like [BenchmarkShortestPath](https://github.com/LdDl/ch/blob/master/bidirectional_ch_test.go#L82)) execute 12 iterations with `k = 0..11`, calculate an `n = 2^k`, but then don't use either of them in the benchmark except for the title.

**To Reproduce**
Run the benchmarks and read source code.

**Expected behavior**
Either `n` or `k` should be used in the benchmark core (not sure what these could be for `BenchmarkShortestPath`, for `BenchmarkShortestPathOneToMany` it could be the number of target nodes).

**Comment by LdDl** [comment]
Wow, we did miss that. Thanks you
Started #29 
1. For `One-To-One` bench we suggest generate graph vertices based on `n=2^k`
2. For `One-To-Many` it depends. May be 2 benchmarks: one is for different graph sizes; second - number of target nodes
3. We need to re-evaluate BenchmarkShortestPathOneToMany and BenchmarkOldWayShortestPathOneToMany (we need to take a look at #27 also) since we've changed PC specs of developer machine

**Comment by LdDl** [comment]
Well, we've just updated PR.
Summary:
1. `BenchmarkShortestPath` - generates graph with `n=2^k`, computes its contraction hierarchies, takes two random vertices and computes shortest path between them.
2. `BenchmarkStaticCaseShortestPath` - just single run on predefined graph (187k vertices) with computing of contraction hierarchies
3. `BenchmarkShortestPathOneToMany` (and old derivative `...OldWay...`) - generates graph with `n=2^k`, computes its contraction hierarchies, takes one random vertex as source and five random vertices as targets and computes shortest paths
4. `BenchmarkTargetNodesShortestPathOneToMany` (and old derivative `...OldWay...`) - takes predefined graph (187k vertices), computes its contraction hierarchies, takes predefined vertex as source, takes random number (`1 up to 2^k`) of random vertices, computes shortest paths
5. `BenchmarkStaticCaseShortestPathOneToMany` (and old derivative `...OldWay...`) - just single run (1 predefined source - 5 predefined targets) on predefined graph (187k vertices) with computing of contraction hierarchies
